version: '2'
services: 
  web:
    build: ./
    ports:
      - "3000:3000"
    environment: 
      MONGO_HOST: "db:27017"
  db:
    restart: always
    image: mongo:3.2
    ports:
      - "27017:27017"
